[package]
name = "rust"
version = "0.1.0"
authors = ["Alexander F Rødseth <rodseth@gmail.com>"]

[dependencies]
docopt = "1"
serde = "1.0" # if you're using `derive(Deserialize)`
serde_derive = "1.0" # if you're using `derive(Deserialize)`

[[bin]]
name = "rust"
path = "main.rs"
